name: Update statistics at midnight

on:
  schedule:
    - cron: '0 0 * * *' # Run every midnight
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node ./utils/generateStatistics.js

      - name: Save JSON file
        uses: actions/upload-artifact@v2
        with:
          name: statistics
          path: ./components/suggestions/result.json
